Factor out configuration into separate config file

diff --git a/tools/scripts/muen-integ b/tools/scripts/muen-integ
--- a/tools/scripts/muen-integ
+++ b/tools/scripts/muen-integ
@@ -1,26 +1,33 @@
 #!/bin/bash
 
-if [ ! $# -eq 2 ]; then
-	echo "Usage: $0 <commit> <build ID>"
+if [ ! $# -eq 3 ]; then
+	echo "Usage: $0 <config_file> <commit> <build ID>"
 	exit 1
 fi
+
+CONFIG=$1
+COMMIT=$2
+BUILDID=$3
+
+if [ ! -f $CONFIG ]; then
+	echo "Unable to read config file '$CONFIG'"
+	exit 1
+fi
+
+config_header=$(head -n 1 $CONFIG)
+
+if [ "$config_header" != "### muen_integ_config ###" ]; then
+	echo "Invalid config file '$CONFIG'"
+	exit 1
+fi
+
+source $CONFIG
 
 SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 WORKDIR=$SCRIPTDIR/../..
 
-COMMIT=$1
-BUILDID=$2
 HARBOR="Harbormaster build http://muen-builder.codelabs.local/B$BUILDID"
-
-ROOT=$HOME/Builds
-LOGDIR=$ROOT/logs/$BUILDID
-LOGFILE=$LOGDIR/build.log
 SAVE_ARTIFACTS=0
-LOCK=/tmp/muen-integ.running
-
-# mail settings
-RECIPIENTS="reet@codelabs.ch ken@codelabs.ch"
-SENDER="muen.builder@gmail.com"
 
 # servers
 PID_HTTP=0
